apiVersion: v1
kind: Service
metadata:
  name: {{ include "carwebsitelunch.fullname" . }}
spec:
  type: NodePort
  ports:
    - port: {{ .Values.service.port }}
      targetPort: {{ .Values.service.port }}
      nodePort: {{ .Values.service.nodePort }}
      protocol: TCP
      name: http
  selector:
    app: {{ include "carwebsitelunch.name" . }}
